#!/usr/bin/env python3
"""Generate manuscript figures and LaTeX macros from committed result reports."""

from __future__ import annotations

import json
import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


PROJECT = Path(__file__).resolve().parents[2]
PAPER = Path(__file__).resolve().parents[1]
REPORTS = PROJECT / "reports"
FIGURES = PAPER / "figures"
GENERATED = PAPER / "generated"

COLORS = {
    "ar_b1": "#1F4E79",
    "ao_b32": "#D97732",
    "random_b32": "#2A8C82",
    "ef_b32": "#8A5FA8",
    "gsm8k": "#3D6FA6",
    "math500": "#B85C38",
}
LABELS = {
    "ar_b1": "Sequential ($B=1$)",
    "ao_b32": "Confidence-first ($B=32$)",
    "random_b32": "Random ($B=32$)",
    "ef_b32": "Entropy-first ($B=32$)",
}


def read_json(path: Path) -> dict:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def phase2_tables() -> dict:
    text = (REPORTS / "phase2_optionB_results_20260906.md").read_text(encoding="utf-8")

    primary = re.search(
        r"\| Pooled \|\s*([-+0-9.]+)\s*\|\s*\[([-+0-9.]+),\s*([-+0-9.]+)\]",
        text,
    )
    if primary is None:
        raise ValueError("Could not parse Option B primary endpoint")

    absolute_block = text.split("The absolute pooled CoverageAUC values are:", 1)[1].split(
        "The adjacent pooled contrasts are:", 1
    )[0]
    absolute = {}
    for match in re.finditer(
        r"^\|\s*(1|8|16|32)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|$",
        absolute_block,
        flags=re.MULTILINE,
    ):
        block = int(match.group(1))
        absolute[block] = {
            "pooled": float(match.group(2)),
            "gsm8k": float(match.group(3)),
            "math500": float(match.group(4)),
        }

    adjacent_block = text.split("The adjacent pooled contrasts are:", 1)[1].split(
        "Accordingly,", 1
    )[0]
    adjacent = []
    for match in re.finditer(
        r"^\|\s*B=(\d+) to B=(\d+)\s*\|\s*([-+0-9.]+)\s*\|\s*\[([-+0-9.]+),\s*([-+0-9.]+)\]",
        adjacent_block,
        flags=re.MULTILINE,
    ):
        adjacent.append(
            {
                "left": int(match.group(1)),
                "right": int(match.group(2)),
                "point": float(match.group(3)),
                "low": float(match.group(4)),
                "high": float(match.group(5)),
            }
        )

    precision_block = text.split("## 5. Precision-diversity trade-off", 1)[1].split(
        "Increasing order freedom", 1
    )[0]
    precision = {}
    for match in re.finditer(
        r"^\|\s*(1|8|16|32)\s*\|\s*([0-9.]+)\s*\|\s*([0-9.]+)\s*\|$",
        precision_block,
        flags=re.MULTILINE,
    ):
        precision[int(match.group(1))] = {
            "pass1": float(match.group(2)),
            "pass16": float(match.group(3)),
        }

    if len(absolute) != 4 or len(adjacent) != 3 or len(precision) != 4:
        raise ValueError("Option B tables were parsed incompletely")

    return {
        "primary": {
            "point": float(primary.group(1)),
            "low": float(primary.group(2)),
            "high": float(primary.group(3)),
        },
        "absolute": absolute,
        "adjacent": adjacent,
        "precision": precision,
    }


def pooled_policy_curves(random_report: dict) -> dict:
    curves = {}
    for policy in ("ar_b1", "ao_b32", "random_b32", "ef_b32"):
        curves[policy] = {}
        for k in (1, 2, 4, 8, 16, 32, 64):
            key = f"pass_at_{k}"
            curves[policy][k] = np.mean(
                [random_report["summaries"][task][policy][key] for task in ("gsm8k", "math500")]
            )
    return curves


def write_macros(
    phase2: dict,
    condition_a: dict,
    random_report: dict,
    gate1: dict,
    postreview: dict,
) -> None:
    p1 = phase2["primary"]
    ca = condition_a["primary"]["pooled"]
    rand = random_report["primary"]["pooled"]

    gate_assoc = gate1["gate1"]["condition_2_bci"]["pooled"]
    gate_mae = gate1["gate1"]["condition_2_bci"]["mae_delta"]
    new48 = postreview["random_extension"]["new48_high_budget_mean_k16_32"]
    block_grids = postreview["block_size"]["b32_minus_b1_grid_sensitivity"]
    random_sequential_grids = random_report["secondary_pairwise"]["random_minus_ar_b1"]["grids"]

    lines = [
        "% Auto-generated by scripts/generate_manuscript_assets.py. Do not edit.",
        f"\\newcommand{{\\OptionBPoint}}{{{p1['point']:.3f}}}",
        f"\\newcommand{{\\OptionBLow}}{{{p1['low']:.3f}}}",
        f"\\newcommand{{\\OptionBHigh}}{{{p1['high']:.3f}}}",
        f"\\newcommand{{\\ConditionAPoint}}{{{ca['point']:.3f}}}",
        f"\\newcommand{{\\ConditionALow}}{{{ca['ci_low']:.3f}}}",
        f"\\newcommand{{\\ConditionAHigh}}{{{ca['ci_high']:.3f}}}",
        f"\\newcommand{{\\RandomPrimaryPoint}}{{{rand['point']:+.3f}}}",
        f"\\newcommand{{\\RandomPrimaryLow}}{{{rand['ci_low']:+.3f}}}",
        f"\\newcommand{{\\RandomPrimaryHigh}}{{{rand['ci_high']:+.3f}}}",
        f"\\newcommand{{\\BCIRho}}{{{gate_assoc['point']:+.3f}}}",
        f"\\newcommand{{\\BCIRhoLow}}{{{gate_assoc['ci_low']:+.3f}}}",
        f"\\newcommand{{\\BCIRhoHigh}}{{{gate_assoc['ci_high']:+.3f}}}",
        f"\\newcommand{{\\BCIMAE}}{{{gate_mae['point']:+.6f}}}",
        f"\\newcommand{{\\RandomNewPoint}}{{{new48['point']:+.3f}}}",
        f"\\newcommand{{\\RandomNewLow}}{{{new48['ci_low']:+.3f}}}",
        f"\\newcommand{{\\RandomNewHigh}}{{{new48['ci_high']:+.3f}}}",
        f"\\newcommand{{\\RandomSequentialLowPoint}}{{{random_sequential_grids['low_k2_4_8_16']['point']:+.3f}}}",
        f"\\newcommand{{\\RandomSequentialLowLow}}{{{random_sequential_grids['low_k2_4_8_16']['ci_low']:+.3f}}}",
        f"\\newcommand{{\\RandomSequentialLowHigh}}{{{random_sequential_grids['low_k2_4_8_16']['ci_high']:+.3f}}}",
        f"\\newcommand{{\\RandomSequentialFullPoint}}{{{random_sequential_grids['full_k4_8_16_32_64']['point']:+.3f}}}",
        f"\\newcommand{{\\RandomSequentialFullLow}}{{{random_sequential_grids['full_k4_8_16_32_64']['ci_low']:+.3f}}}",
        f"\\newcommand{{\\RandomSequentialFullHigh}}{{{random_sequential_grids['full_k4_8_16_32_64']['ci_high']:+.3f}}}",
        f"\\newcommand{{\\BlockLowGridPoint}}{{{block_grids['low_k1_2_4_8']['point']:+.3f}}}",
        f"\\newcommand{{\\BlockLowGridLow}}{{{block_grids['low_k1_2_4_8']['ci_low']:+.3f}}}",
        f"\\newcommand{{\\BlockLowGridHigh}}{{{block_grids['low_k1_2_4_8']['ci_high']:+.3f}}}",
        f"\\newcommand{{\\BlockHighGridPoint}}{{{block_grids['high_k16_32_64']['point']:+.3f}}}",
        f"\\newcommand{{\\BlockHighGridLow}}{{{block_grids['high_k16_32_64']['ci_low']:+.3f}}}",
        f"\\newcommand{{\\BlockHighGridHigh}}{{{block_grids['high_k16_32_64']['ci_high']:+.3f}}}",
        "",
    ]
    (GENERATED / "paper_numbers.tex").write_text("\n".join(lines), encoding="utf-8")


def write_postreview_tables(postreview: dict, temperature: dict) -> None:
    majority = postreview["majority_vote"]
    labels = {
        "ar_b1": "Sequential ($B=1$)",
        "ao_b32": "CF ($B=32$)",
        "random_b32": "RND ($B=32$)",
        "ef_b32": "EF ($B=32$)",
    }
    lines = [
        "% Auto-generated by scripts/generate_manuscript_assets.py. Do not edit.",
        "\\newcommand{\\PostreviewMajorityVoteRows}{%",
    ]
    for policy in labels:
        values = " & ".join(
            f"{majority[policy][str(k)]['pooled']:.3f}" for k in (1, 2, 4, 8, 16, 32, 64)
        )
        lines.append(f"{labels[policy]} & {values} \\\\")
    lines.append("}")
    (GENERATED / "postreview_majority_vote_rows.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )

    accounting = postreview["generation_accounting"]
    account_labels = {
        "phase0_signal": "Phase-0 signal",
        "phase1_calibration": "Phase-1 calibration",
        "phase1_heldout_screening": "Held-out screening",
        "phase1_primary_extension": "Primary extension",
        "phase2_block_size_extension": "Block-size extension",
        "condition_a_entropy_first": "Entropy-first intervention",
        "random_policy_extension": "Random-policy extension",
    }
    lines = [
        "% Auto-generated by scripts/generate_manuscript_assets.py. Do not edit.",
        "\\newcommand{\\GenerationAccountingRows}{%",
    ]
    for key, label in account_labels.items():
        lines.append(f"{label} & {accounting['rows'][key]:,} \\\\")
    new_generations = temperature["validation"]["new_artifacts"]["present_and_valid"]
    lines.append(f"Temperature extension & {new_generations:,} \\\\")
    lines.append(f"\\textbf{{Total}} & \\textbf{{{accounting['total'] + new_generations:,}}} \\\\")
    lines.append("}")
    (GENERATED / "generation_accounting_rows.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )

    difficulty = postreview["math_difficulty"]["levels"]
    lines = [
        "% Auto-generated by scripts/generate_manuscript_assets.py. Do not edit.",
        "\\newcommand{\\MathDifficultyRows}{%",
    ]
    for level, result in difficulty.items():
        policies = result["policies"]
        values = [
            policies[key]["coverage_auc_k4_8_16_32_64"]
            for key in ("ar_b1", "ao_b32", "random_b32", "ef_b32")
        ]
        formatted = " & ".join(f"{value:.3f}" for value in values)
        lines.append(f"{level.replace('Level ', '')} & {result['queries']} & {formatted} \\\\")
    lines.append("}")
    (GENERATED / "postreview_math_difficulty_rows.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def configure_plotting() -> None:
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 9,
            "axes.labelsize": 9,
            "axes.titlesize": 10,
            "legend.fontsize": 7.8,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def save_figure(fig: plt.Figure, stem: str) -> None:
    fig.savefig(FIGURES / f"{stem}.pdf", bbox_inches="tight", pad_inches=0.02)
    fig.savefig(FIGURES / f"{stem}.png", dpi=220, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


def figure_block_size(phase2: dict) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.45), gridspec_kw={"width_ratios": [1.08, 0.92]})
    blocks = np.array([1, 8, 16, 32])
    x = np.arange(len(blocks))
    for task, label in (("gsm8k", "GSM8K"), ("math500", "MATH-500")):
        vals = [phase2["absolute"][int(b)][task] for b in blocks]
        axes[0].plot(x, vals, marker="o", ms=4, lw=1.2, alpha=0.65, color=COLORS[task], label=label)
    pooled = [phase2["absolute"][int(b)]["pooled"] for b in blocks]
    axes[0].plot(x, pooled, marker="D", ms=5, lw=2.2, color="#222222", label="equal-task pooled")
    axes[0].axvspan(-0.08, 1.08, color="#E8EEF3", alpha=0.7, zorder=-2)
    axes[0].set_xticks(x)
    axes[0].set_xticklabels([str(v) for v in blocks])
    axes[0].set_xlabel("eligible-set block size $B$")
    axes[0].set_ylabel("CoverageAUC")
    axes[0].set_title("a   Only the first tested widening resolves", loc="left", weight="bold")
    axes[0].legend(frameon=False, loc="best")

    labels = [f"{row['left']} to {row['right']}" for row in phase2["adjacent"]]
    points = np.array([row["point"] for row in phase2["adjacent"]])
    lows = np.array([row["low"] for row in phase2["adjacent"]])
    highs = np.array([row["high"] for row in phase2["adjacent"]])
    err = np.vstack([points - lows, highs - points])
    axes[1].axhline(0, color="#777777", lw=0.8)
    axes[1].errorbar(np.arange(3), points, yerr=err, fmt="o", ms=5, capsize=3, color="#333333")
    axes[1].set_xticks(np.arange(3))
    axes[1].set_xticklabels(labels)
    axes[1].set_xlabel("adjacent change in $B$")
    axes[1].set_ylabel(r"$\Delta$ CoverageAUC")
    axes[1].set_title("b   Later width increments are unresolved", loc="left", weight="bold")
    fig.tight_layout(w_pad=1.8)
    save_figure(fig, "fig2_block_size")


def figure_policy_frontier(random_report: dict) -> None:
    curves = pooled_policy_curves(random_report)
    k = np.array([1, 2, 4, 8, 16, 32, 64])
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.75), gridspec_kw={"width_ratios": [1.12, 0.88]})
    styles = {
        "ar_b1": ("D", "-"),
        "ao_b32": ("o", "-"),
        "random_b32": ("s", "-"),
        "ef_b32": ("^", "--"),
    }
    handles = []
    legend_labels = []
    for policy in styles:
        marker, line = styles[policy]
        handle, = axes[0].plot(
            k,
            [curves[policy][int(v)] for v in k],
            marker=marker,
            ls=line,
            lw=1.7,
            ms=4,
            color=COLORS[policy],
            label=LABELS[policy],
        )
        handles.append(handle)
        legend_labels.append(LABELS[policy])
    axes[0].set_xscale("log", base=2)
    axes[0].set_xticks(k)
    axes[0].set_xticklabels([str(v) for v in k])
    axes[0].set_ylim(0.35, 0.91)
    axes[0].set_xlabel("sampling budget $k$")
    axes[0].set_ylabel("equal-task pooled Pass@$k$")
    fig.legend(
        handles,
        legend_labels,
        frameon=False,
        ncol=2,
        loc="lower left",
        bbox_to_anchor=(0.04, 0.01),
        columnspacing=0.9,
        handlelength=1.8,
    )
    axes[0].set_title("a   Policies reshape the coverage frontier", loc="left", weight="bold")

    per_k = random_report["secondary_pairwise"]["random_minus_ao_b32"]["per_k"]
    point = np.array([per_k[str(v)]["pooled"]["point"] for v in k])
    low = np.array([per_k[str(v)]["pooled"]["ci_low"] for v in k])
    high = np.array([per_k[str(v)]["pooled"]["ci_high"] for v in k])
    axes[1].axhline(0, color="#666666", lw=0.9)
    axes[1].fill_between(k, low, high, color=COLORS["random_b32"], alpha=0.16, linewidth=0)
    axes[1].plot(k, point, marker="s", color=COLORS["random_b32"], lw=1.7, ms=4)
    axes[1].set_xscale("log", base=2)
    axes[1].set_xticks(k)
    axes[1].set_xticklabels([str(v) for v in k])
    axes[1].set_xlabel("sampling budget $k$")
    axes[1].set_ylabel("Random $-$ confidence-first")
    axes[1].text(1.1, -0.115, "confidence-first favored", color=COLORS["ao_b32"], fontsize=7.5)
    axes[1].text(11.5, 0.077, "random favored", color=COLORS["random_b32"], fontsize=7.5)
    axes[1].set_title("b   The paired contrast changes sign", loc="left", weight="bold")
    fig.tight_layout(w_pad=1.8, rect=(0, 0.20, 1, 1))
    save_figure(fig, "fig3_policy_frontier")


def figure_diversity(random_report: dict) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.45), sharey=True)
    for ax, task, title in zip(axes, ("gsm8k", "math500"), ("GSM8K", "MATH-500")):
        for policy in ("ar_b1", "ao_b32", "random_b32", "ef_b32"):
            summary = random_report["summaries"][task][policy]
            entropy = summary["diversity"]["k64"]["mean_answer_entropy"]
            high_coverage = np.mean([summary[f"pass_at_{k}"] for k in (16, 32, 64)])
            ax.scatter(entropy, high_coverage, s=45, color=COLORS[policy], marker={"ar_b1": "D", "ao_b32": "o", "random_b32": "s", "ef_b32": "^"}[policy], zorder=3)
            ax.annotate(LABELS[policy].split(" (")[0], (entropy, high_coverage), xytext=(4, 3), textcoords="offset points", fontsize=7.2)
        ax.grid(color="#DDDDDD", lw=0.5, alpha=0.65)
        ax.set_xlabel("parsed-answer entropy at $k=64$")
        ax.set_title(title, weight="bold")
    axes[0].set_ylabel(r"mean Pass@$k$, $k\in\{16,32,64\}$")
    fig.suptitle("More answer-string diversity is not sufficient for more correct coverage", y=1.03, fontsize=10, weight="bold")
    fig.tight_layout(w_pad=1.5)
    save_figure(fig, "fig4_diversity")


def write_temperature_assets(report: dict, exploratory: dict, postreview: dict) -> None:
    lines = ["% Auto-generated from the audited temperature reports. Do not edit."]

    def macro(name: str, value: float, signed: bool = False) -> None:
        rendered = f"{value:+.3f}" if signed else f"{value:.3f}"
        lines.append(f"\\newcommand{{\\{name}}}{{{rendered}}}")

    for key, label in (("t09", "Nine"), ("t12", "Twelve")):
        for endpoint, endpoint_label in (("low", "Low"), ("high", "High")):
            result = report["primary"]["endpoints"][f"{key}_{endpoint}"]
            stem = f"Temp{label}{endpoint_label}"
            macro(stem + "Point", result["point"], signed=True)
            macro(stem + "Lower", result["simultaneous_95_ci"][0], signed=True)
            macro(stem + "Upper", result["simultaneous_95_ci"][1], signed=True)
    result = exploratory["interactions"]["random_vs_cf_t1.2_minus_t0.6_low"]
    macro("TempInteractionPoint", result["point"], signed=True)
    macro("TempInteractionLower", result["raw_95_ci"][0], signed=True)
    macro("TempInteractionUpper", result["raw_95_ci"][1], signed=True)
    new_count = report["validation"]["new_artifacts"]["present_and_valid"]
    total = postreview["generation_accounting"]["total"] + new_count
    lines.append(f"\\newcommand{{\\TemperatureNewCount}}{{{new_count:,}}}")
    lines.append(f"\\newcommand{{\\StudyGenerationCount}}{{{total:,}}}")

    trace = exploratory["trace_sample"]["cells"]
    for temp, label in (("0.6", "Base"), ("0.9", "Mid"), ("1.2", "High")):
        macro(f"TempCFEntropy{label}", trace[temp]["confidence_first"]["selected_entropy"])
    for temp, label in (("0.6", "Base"), ("1.2", "High")):
        curve = report["secondary_curves"][temp]["random"]["equal_task_pooled"]
        vote = report["secondary_diagnostics"][temp]["random"]["by_k"]["32"]
        macro(f"TempRandomGap{label}", curve["32"] - vote["majority_vote_accuracy_ties_fractional"])

    lines.append("\\newcommand{\\TemperaturePrimaryRows}{%")
    for temp, key in (("0.9", "t09"), ("1.2", "t12")):
        row = [temp]
        for endpoint in ("low", "high"):
            result = report["primary"]["endpoints"][f"{key}_{endpoint}"]
            low, high = result["simultaneous_95_ci"]
            row.extend([f"${result['point']:+.3f}$", f"$[{low:+.3f},{high:+.3f}]$"])
        lines.append(" & ".join(row) + r" \\")
    lines.append("}")

    labels = {"confidence_first": "CF", "random": "RND", "sequential": "Sequential"}
    lines.append("\\newcommand{\\TemperatureDiagnosticRows}{%")
    for temp in ("0.6", "0.9", "1.2"):
        for schedule, label in labels.items():
            curve = report["secondary_curves"][temp][schedule]["equal_task_pooled"]
            diagnostic = report["secondary_diagnostics"][temp][schedule]
            k32 = diagnostic["by_k"]["32"]
            row = [temp, label, f"{curve['1']:.3f}", f"{curve['32']:.3f}",
                   f"{k32['majority_vote_accuracy_ties_fractional']:.3f}",
                   f"{diagnostic['quality']['mean_whitespace_tokens']:.1f}",
                   f"{k32['mean_unique_parsed_answers']:.2f}"]
            lines.append(" & ".join(row) + r" \\")
    lines.append("}")
    lines.append("\\newcommand{\\TemperatureTraceRows}{%")
    for schedule, label in labels.items():
        row = [label]
        for temp in ("0.6", "0.9", "1.2"):
            cell = trace[temp][schedule]
            row.extend([f"{cell['selected_entropy']:.3f}", f"{cell['eligible_entropy']:.3f}"])
        lines.append(" & ".join(row) + r" \\")
    lines.append("}")
    (GENERATED / "temperature_numbers.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def figure_temperature_frontier(report: dict) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(7.0, 2.35), sharex=True, sharey=True)
    k = [1, 2, 4, 8, 16, 32]
    policies = [("confidence_first", "ao_b32", "o", "CF"),
                ("random", "random_b32", "s", "RND"),
                ("sequential", "ar_b1", "D", "Sequential")]
    for ax, temp in zip(axes, ("0.6", "0.9", "1.2")):
        for schedule, color_key, marker, label in policies:
            curve = report["secondary_curves"][temp][schedule]["equal_task_pooled"]
            ax.plot(k, [curve[str(v)] for v in k], color=COLORS[color_key],
                    marker=marker, ms=3.2, lw=1.5, label=label)
        ax.set_xscale("log", base=2)
        ax.set_xticks(k, [str(v) for v in k])
        ax.set_ylim(0, 1)
        ax.set_xlabel("sampling budget $k$")
        ax.set_title(f"$T={temp}$" + (" (reused)" if temp == "0.6" else " (new)"))
        ax.grid(axis="y", color="#DDDDDD", lw=0.5)
    axes[0].set_ylabel("equal-task pooled Pass@$k$")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3, frameon=False,
               bbox_to_anchor=(0.52, 0.0))
    fig.tight_layout(w_pad=0.7, rect=(0, 0.12, 1, 1))
    save_figure(fig, "fig5_temperature_frontier")


def main() -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    GENERATED.mkdir(parents=True, exist_ok=True)
    phase2 = phase2_tables()
    condition_a = read_json(REPORTS / "heldout_analysis_v1" / "condition_a_report.json")
    random_report = read_json(
        REPORTS / "random_extension_results_20260914" / "random_extension_report.json"
    )
    gate1 = read_json(REPORTS / "heldout_analysis_v1" / "phase1_gate1_report.json")
    postreview = read_json(
        REPORTS / "postreview_cpu_audits_20260914" / "postreview_cpu_audits.json"
    )
    temperature_dir = REPORTS / "temperature_extension_results_20260927"
    temperature = read_json(temperature_dir / "temperature_extension_analysis_v1.json")
    exploratory = read_json(temperature_dir / "temperature_extension_exploratory_v2.json")
    configure_plotting()
    write_macros(phase2, condition_a, random_report, gate1, postreview)
    write_postreview_tables(postreview, temperature)
    write_temperature_assets(temperature, exploratory, postreview)
    # Figure 1 is a manually reviewed asset; do not overwrite it during builds.
    figure_block_size(phase2)
    figure_policy_frontier(random_report)
    figure_diversity(random_report)
    figure_temperature_frontier(temperature)
    print(f"Generated manuscript assets in {PAPER}")


if __name__ == "__main__":
    main()
