#!/usr/bin/env python3
"""Draw Figure 1: the decoding decision studied in the paper.

Panel (a) is a schematic of the evaluated implementation: every schedule
commits exactly one token per neural function evaluation (NFE); B only changes
which masked positions are eligible. Panel (b) is an explicitly conceptual
sketch of a budget-dependent policy crossing. It contains no data; the
empirical frontiers and intervals are in Figures 3 and 5.

This asset is reviewed manually and is not regenerated by ``make``. Run it
directly after editing:

    python figures/fig1_overview.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyBboxPatch, Rectangle

OUT = Path(__file__).resolve().parent

INK = "#1F2A3A"
MUTED = "#6B7280"
MASK_FILL = "#F3F4F6"
MASK_EDGE = "#9CA3AF"
OLD_FILL = "#D6DEE8"
NEW_FILL = "#1F4E79"
ELIGIBLE_EDGE = "#B7791F"
COLORS = {
    "cf": "#D97732",
    "rnd": "#2A8C82",
    "ef": "#8A5FA8",
    "seq": "#1F4E79",
}

CELL = 2.55
GAP = 0.35
N_CELLS = 8


def draw_state(ax, x0: float, y0: float, committed: dict[int, str], newest: int, eligible: set[int]) -> None:
    """Draw one sequence state of eight positions starting at (x0, y0)."""
    for i in range(N_CELLS):
        x = x0 + i * (CELL + GAP)
        pos = i + 1
        if pos == newest:
            face, edge, text, color, weight = NEW_FILL, NEW_FILL, committed[pos], "white", "bold"
        elif pos in committed:
            face, edge, text, color, weight = OLD_FILL, "#8BA0B8", committed[pos], INK, "normal"
        else:
            face, edge, text, color, weight = MASK_FILL, MASK_EDGE, "M", MUTED, "normal"
        lw = 1.3 if (pos in eligible and pos not in committed) else 0.6
        if pos in eligible and pos not in committed:
            edge = ELIGIBLE_EDGE
        ax.add_patch(Rectangle((x, y0), CELL, CELL * 1.25, facecolor=face, edgecolor=edge, lw=lw))
        ax.text(x + CELL / 2, y0 + CELL * 0.62, text, ha="center", va="center", fontsize=6.6, color=color, weight=weight)


def state_width() -> float:
    return N_CELLS * CELL + (N_CELLS - 1) * GAP


def panel_a(ax) -> None:
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 62)
    ax.axis("off")
    ax.text(0, 60.5, "(a) Where order freedom enters", fontsize=9.9, weight="bold", color=INK, va="top")
    ax.text(0, 55.2, "Every schedule uses 256 NFEs and commits exactly one token after each NFE.",
            fontsize=7.6, color=MUTED, va="top")

    # Key for the cell styles.
    key_y = 44.2
    key_items = (
        (MASK_FILL, ELIGIBLE_EDGE, 1.3, "eligible mask"),
        (NEW_FILL, NEW_FILL, 0.6, "committed now"),
        (OLD_FILL, "#8BA0B8", 0.6, "committed earlier"),
        (MASK_FILL, MASK_EDGE, 0.6, "ineligible mask"),
    )
    for j, (face, edge, lw, label) in enumerate(key_items):
        x = (20.5, 38.0, 57.0, 79.0)[j]
        ax.add_patch(Rectangle((x, key_y), 1.8, 2.2, facecolor=face, edgecolor=edge, lw=lw))
        ax.text(x + 2.6, key_y + 1.1, label, fontsize=7.0, color=MUTED, va="center")

    x_states = [20.5, 47.5, 74.5]
    for x, label in zip(x_states, ("after NFE $t$", "after NFE $t{+}1$", "after NFE $t{+}2$")):
        ax.text(x + state_width() / 2, 49.0, label, ha="center", fontsize=7.8, color=INK)
    for left, right in zip(x_states[:-1], x_states[1:]):
        for y in (38.6, 21.6):
            ax.annotate("", xy=(right - 0.5, y), xytext=(left + state_width() + 0.5, y),
                        arrowprops={"arrowstyle": "-|>", "color": MUTED, "lw": 0.8})

    # Row 1: sequential, B = 1. The eligible set is the next position only.
    ax.text(0, 40.6, "Sequential", fontsize=8.0, weight="bold", color=COLORS["seq"], va="center")
    ax.text(0, 36.6, "$B=1$", fontsize=8.2, color=INK, va="center")
    seq_states = [
        ({1: "w1"}, 1, {2}),
        ({1: "w1", 2: "w2"}, 2, {3}),
        ({1: "w1", 2: "w2", 3: "w3"}, 3, {4}),
    ]
    for x, (committed, newest, eligible) in zip(x_states, seq_states):
        draw_state(ax, x, 36.6, committed, newest, eligible)
    ax.text(x_states[0], 32.6, "eligible set = next position only; the ranking rule is inert",
            fontsize=7.2, color=MUTED, va="center")

    # Row 2: block-parallel, B > 1 (one 8-position block shown schematically).
    ax.text(0, 23.6, "Block-parallel", fontsize=8.0, weight="bold", color=INK, va="center")
    ax.text(0, 19.6, "$B>1$", fontsize=8.2, color=INK, va="center")
    block = set(range(1, 9))
    block_states = [
        ({3: "w3"}, 3, block),
        ({3: "w3", 7: "w7"}, 7, block),
        ({1: "w1", 3: "w3", 7: "w7"}, 1, block),
    ]
    for x, (committed, newest, eligible) in zip(x_states, block_states):
        draw_state(ax, x, 19.6, committed, newest, eligible)
    ax.text(x_states[0], 15.6,
            "every masked position in the active block is eligible; the rule picks one per NFE",
            fontsize=7.2, color=MUTED, va="center")

    # Ranking rules used inside the active block.
    rules = (
        ("cf", "Confidence-first (CF)", r"max $p_\theta(\tilde x_i \mid x_t)$"),
        ("rnd", "Random (RND)", r"$u_i \sim \mathcal{U}(0,1)$"),
        ("ef", "Entropy-first (EF)", r"max $H[p_\theta(\cdot \mid x_t)_i]$"),
    )
    for j, (key, name, formula) in enumerate(rules):
        x = 20.5 + j * 27.0
        ax.add_patch(FancyBboxPatch((x, 1.0), 25.0, 9.2, boxstyle="round,pad=0.25,rounding_size=1.2",
                                    facecolor="white", edgecolor=COLORS[key], lw=1.1))
        ax.text(x + 12.5, 7.6, name, ha="center", va="center", fontsize=7.2, weight="bold", color=COLORS[key])
        ax.text(x + 12.5, 3.4, formula, ha="center", va="center", fontsize=8.0, color=INK)
    ax.text(0, 7.6, "Ranking", fontsize=8.2, weight="bold", color=INK, va="center")
    ax.text(0, 3.6, "rule ($B>1$)", fontsize=7.6, color=INK, va="center")


def panel_b(ax) -> None:
    k = np.logspace(0, 6, 200, base=2)
    z = np.log2(k) / 6
    concentrated = 0.55 + 0.26 * (1 - np.exp(-3.0 * z))
    exploratory = 0.40 + 0.50 * (1 - np.exp(-2.4 * z))
    ax.axvspan(1, 2.3, color="#FBEDE3", lw=0, zorder=-3)
    ax.axvspan(16, 64, color="#E6F2F0", lw=0, zorder=-3)
    ax.plot(k, concentrated, color=COLORS["cf"], lw=1.8)
    ax.plot(k, exploratory, color=COLORS["rnd"], lw=1.8, ls="--")
    ax.text(1.12, 0.905, "few samples:\nprecision", fontsize=7.0, color="#9A4A16", va="top")
    ax.text(60, 0.48, "many samples:\ncoverage", fontsize=7.0, color="#1D6159", ha="right", va="bottom")
    ax.text(62, 0.752, "concentrated", fontsize=7.2, color=COLORS["cf"], ha="right", va="top")
    ax.text(62, 0.885, "exploratory", fontsize=7.2, color=COLORS["rnd"], ha="right", va="bottom")
    ax.set_xscale("log", base=2)
    ax.set_xticks([1, 4, 16, 64])
    ax.set_xticklabels(["1", "4", "16", "64"])
    ax.set_yticks([])
    ax.set_xlim(1, 64)
    ax.set_ylim(0.36, 0.95)
    ax.set_xlabel("sampling budget $k$", fontsize=8.0)
    ax.set_ylabel("Pass@$k$ (schematic)", fontsize=8.0)
    ax.tick_params(labelsize=7)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    ax.set_title("(b) Conceptual crossing", fontsize=9.9, weight="bold", color=INK, loc="left")
    ax.text(0.98, 0.03, "illustrative; not data", transform=ax.transAxes, ha="right", fontsize=7.0,
            color=MUTED, style="italic")


def main() -> None:
    plt.rcParams.update({"font.family": "serif", "pdf.fonttype": 42, "ps.fonttype": 42})
    fig = plt.figure(figsize=(7.0, 2.55))
    ax_a = fig.add_axes((0.0, 0.0, 0.70, 1.0))
    ax_b = fig.add_axes((0.775, 0.17, 0.215, 0.70))
    panel_a(ax_a)
    panel_b(ax_b)
    fig.savefig(OUT / "fig1_overview.pdf", bbox_inches="tight", pad_inches=0.02)
    fig.savefig(OUT / "fig1_overview.png", dpi=220, bbox_inches="tight", pad_inches=0.02)
    plt.close(fig)


if __name__ == "__main__":
    main()
